name: Tests

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      
      - name: Build library
        run: make library
      
      - name: Run test - hash creation
        run: make test_hash_create DEBUG_MODE=true
      
      - name: Run test - hashtable creation
        run: make test_hashtable_create DEBUG_MODE=true
