name: Tests

on:
  push:
    branch:
      dev
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3
      
      - name: Build library
        run: make library
      
      - name: Run test - hash creation
        run: make test_hash_create DEBUG_MODE=true
